name: Deploy to Server

on:
  push:
    branches:
      - main  # Trigger khi có push vào nhánh main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22.14.0'  # Phiên bản Node.js

    - name: Install dependencies
      run: npm ci  # Cài đặt các dependencies

    - name: Build the project
      run: npm run build  # Chạy npm run build để build ứng dụng

    - name: Deploy to server
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.SERVER_HOST }}  # Lấy giá trị từ GitHub Secrets
        username: ${{ secrets.SERVER_USER }}  # Lấy giá trị từ GitHub Secrets
        key: ${{ secrets.SERVER_KEY }}  # Lấy giá trị từ GitHub Secrets
        port: 4433  # Cổng SSH là 443
        script: |
          # Cập nhật PATH để bao gồm các công cụ npm và pm2 từ NVM
          export PATH=$PATH:/root/.nvm/versions/node/v22.14.0/bin

          # Kiểm tra lại npm và pm2
          which npm
          which pm2

          cd /var/www/web-app-nhacuayensao/  # Đến thư mục chứa project trên server
          git pull origin main  # Pull latest code từ repository
          npm ci  # Cài đặt lại dependencies nếu có thay đổi
          npm run build  # Xây dựng lại ứng dụng
          pm2 restart web-app-nhacuayensao  # Restart ứng dụng với PM2
